---
apiVersion: v1
kind: Namespace
metadata:
  name: express
---
apiVersion: apps/v1
kind: Deployment
# pod 생성, 관리
metadata:
  name: web-deployment
  namespace: express
  labels: # 이름 붙이기
    app: web
spec:
  replicas: 3 # pod 1개 고정
  selector:
    matchLabels:
      app: web
  template: # pod 정의
    metadata:
      labels:
        app: web
    spec: # 컨테이너 구성
      containers:
      - name: nginx
        image: nginx
        ports:
        - containerPort: 80
---
apiVersion: v1
kind: Service
metadata:
  name: olive-web
  namespace: express
spec:
  selector: # LB진입시 어떤 pod에게 보낼것인가
    app: web
  ports:
  - protocol: TCP
    port: 80 # loadbalancer 진입 포트
    targetPort: 80 # pod에 보낼때 이용포트트
  type: LoadBalancer
